// <auto-generated />
namespace McSntt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedBoats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedBoats));
        
        string IMigrationMetadata.Id
        {
            get { return "201404161150398_Added-Boats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
